project:
  type: book
  output-dir: docs

book:
  title: "Skript Mathematik 2c"
  author: "Levin Angst"
  date: today
  favicon: favicon.png
  description: Dieses Buch umfasst den Unterrichtsstoff für das Jahr 2025/26
  keyword: "test, unterricht"
  url: "https://angstle.github.io/mat2c/"
  page-navigation: true
  sidebar:
    logo: logo_2.png
    search: true
  repo-subdir: book
  repo-branch: main
  image: logo_2.png

  chapters:
    - index.qmd
    - 1_polynome.qmd
    - 1_1_aufgaben_polynome.qmd
    - 2_wurzeln.qmd
    - 3_flaechen.qmd
    - 4_gleichungen.qmd
    - 5_faktorzerlegung.qmd
    - 6_pythagoras.qmd
    - 7_kreis.qmd


format:
  html:
    mermaid:
      theme: neutral
    theme:
      light: flatly
      dark: superhero
    code-fold: false
    css: custom.css
    mainfont: FiraCode
